// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    incident_id,
    fingerprint,
    labels,
    annotations,
    starts_at,
    ends_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (incident_id, fingerprint) DO UPDATE
SET
    labels = EXCLUDED.labels,
    annotations = EXCLUDED.annotations,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at
RETURNING id, incident_id, fingerprint, labels, annotations, starts_at, ends_at, created_at
`

type CreateAlertParams struct {
	IncidentID  string             `json:"incident_id"`
	Fingerprint string             `json:"fingerprint"`
	Labels      json.RawMessage    `json:"labels"`
	Annotations json.RawMessage    `json:"annotations"`
	StartsAt    time.Time          `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.IncidentID,
		arg.Fingerprint,
		arg.Labels,
		arg.Annotations,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Fingerprint,
		&i.Labels,
		&i.Annotations,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertByFingerprint = `-- name: GetAlertByFingerprint :one
SELECT id, incident_id, fingerprint, labels, annotations, starts_at, ends_at, created_at FROM alerts
WHERE fingerprint = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetAlertByFingerprint(ctx context.Context, fingerprint string) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByFingerprint, fingerprint)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Fingerprint,
		&i.Labels,
		&i.Annotations,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertsByIncidentID = `-- name: GetAlertsByIncidentID :many
SELECT id, incident_id, fingerprint, labels, annotations, starts_at, ends_at, created_at FROM alerts
WHERE incident_id = $1
ORDER BY starts_at DESC
`

func (q *Queries) GetAlertsByIncidentID(ctx context.Context, incidentID string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, getAlertsByIncidentID, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAlerts = `-- name: ListRecentAlerts :many
SELECT id, incident_id, fingerprint, labels, annotations, starts_at, ends_at, created_at FROM alerts
WHERE starts_at > $1
ORDER BY starts_at DESC
`

func (q *Queries) ListRecentAlerts(ctx context.Context, startsAt time.Time) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listRecentAlerts, startsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
