// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package pgstore

import (
	"context"
	"time"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    id,
    service,
    cluster,
    environment,
    severity,
    correlation_key,
    correlation_version,
    state,
    created_at,
    updated_at,
    first_alert_at,
    last_alert_at,
    topology_snapshot,
    remediation_attempts,
    github_pr_url,
    rca_summary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

type CreateIncidentParams struct {
	ID                  string    `json:"id"`
	Service             string    `json:"service"`
	Cluster             string    `json:"cluster"`
	Environment         string    `json:"environment"`
	Severity            string    `json:"severity"`
	CorrelationKey      string    `json:"correlation_key"`
	CorrelationVersion  int32     `json:"correlation_version"`
	State               string    `json:"state"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	FirstAlertAt        time.Time `json:"first_alert_at"`
	LastAlertAt         time.Time `json:"last_alert_at"`
	TopologySnapshot    []byte    `json:"topology_snapshot"`
	RemediationAttempts int32     `json:"remediation_attempts"`
	GithubPrUrl         *string   `json:"github_pr_url"`
	RcaSummary          *string   `json:"rca_summary"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.Service,
		arg.Cluster,
		arg.Environment,
		arg.Severity,
		arg.CorrelationKey,
		arg.CorrelationVersion,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstAlertAt,
		arg.LastAlertAt,
		arg.TopologySnapshot,
		arg.RemediationAttempts,
		arg.GithubPrUrl,
		arg.RcaSummary,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const findOpenByCorrelationKey = `-- name: FindOpenByCorrelationKey :one
SELECT id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary FROM incidents
WHERE correlation_key = $1
  AND state != 'resolved'
  AND last_alert_at > $2
ORDER BY last_alert_at DESC
LIMIT 1
`

type FindOpenByCorrelationKeyParams struct {
	CorrelationKey string    `json:"correlation_key"`
	LastAlertAt    time.Time `json:"last_alert_at"`
}

func (q *Queries) FindOpenByCorrelationKey(ctx context.Context, arg FindOpenByCorrelationKeyParams) (Incident, error) {
	row := q.db.QueryRow(ctx, findOpenByCorrelationKey, arg.CorrelationKey, arg.LastAlertAt)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary FROM incidents
WHERE id = $1
`

func (q *Queries) GetIncidentByID(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const incrementRemediationAttempts = `-- name: IncrementRemediationAttempts :one
UPDATE incidents
SET remediation_attempts = remediation_attempts + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

func (q *Queries) IncrementRemediationAttempts(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, incrementRemediationAttempts, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary FROM incidents
ORDER BY created_at DESC
`

func (q *Queries) ListIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Cluster,
			&i.Environment,
			&i.Severity,
			&i.CorrelationKey,
			&i.CorrelationVersion,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstAlertAt,
			&i.LastAlertAt,
			&i.TopologySnapshot,
			&i.RemediationAttempts,
			&i.GithubPrUrl,
			&i.RcaSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByState = `-- name: ListIncidentsByState :many
SELECT id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary FROM incidents
WHERE state = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIncidentsByState(ctx context.Context, state string) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Cluster,
			&i.Environment,
			&i.Severity,
			&i.CorrelationKey,
			&i.CorrelationVersion,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstAlertAt,
			&i.LastAlertAt,
			&i.TopologySnapshot,
			&i.RemediationAttempts,
			&i.GithubPrUrl,
			&i.RcaSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET
    service = $2,
    cluster = $3,
    environment = $4,
    severity = $5,
    correlation_key = $6,
    correlation_version = $7,
    state = $8,
    updated_at = $9,
    first_alert_at = $10,
    last_alert_at = $11,
    topology_snapshot = $12,
    remediation_attempts = $13,
    github_pr_url = $14,
    rca_summary = $15
WHERE id = $1
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

type UpdateIncidentParams struct {
	ID                  string    `json:"id"`
	Service             string    `json:"service"`
	Cluster             string    `json:"cluster"`
	Environment         string    `json:"environment"`
	Severity            string    `json:"severity"`
	CorrelationKey      string    `json:"correlation_key"`
	CorrelationVersion  int32     `json:"correlation_version"`
	State               string    `json:"state"`
	UpdatedAt           time.Time `json:"updated_at"`
	FirstAlertAt        time.Time `json:"first_alert_at"`
	LastAlertAt         time.Time `json:"last_alert_at"`
	TopologySnapshot    []byte    `json:"topology_snapshot"`
	RemediationAttempts int32     `json:"remediation_attempts"`
	GithubPrUrl         *string   `json:"github_pr_url"`
	RcaSummary          *string   `json:"rca_summary"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.ID,
		arg.Service,
		arg.Cluster,
		arg.Environment,
		arg.Severity,
		arg.CorrelationKey,
		arg.CorrelationVersion,
		arg.State,
		arg.UpdatedAt,
		arg.FirstAlertAt,
		arg.LastAlertAt,
		arg.TopologySnapshot,
		arg.RemediationAttempts,
		arg.GithubPrUrl,
		arg.RcaSummary,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const updateIncidentPR = `-- name: UpdateIncidentPR :one
UPDATE incidents
SET github_pr_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

type UpdateIncidentPRParams struct {
	ID          string  `json:"id"`
	GithubPrUrl *string `json:"github_pr_url"`
}

func (q *Queries) UpdateIncidentPR(ctx context.Context, arg UpdateIncidentPRParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentPR, arg.ID, arg.GithubPrUrl)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const updateIncidentRCA = `-- name: UpdateIncidentRCA :one
UPDATE incidents
SET rca_summary = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

type UpdateIncidentRCAParams struct {
	ID         string  `json:"id"`
	RcaSummary *string `json:"rca_summary"`
}

func (q *Queries) UpdateIncidentRCA(ctx context.Context, arg UpdateIncidentRCAParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentRCA, arg.ID, arg.RcaSummary)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}

const updateIncidentState = `-- name: UpdateIncidentState :one
UPDATE incidents
SET state = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, service, cluster, environment, severity, correlation_key, correlation_version, state, created_at, updated_at, first_alert_at, last_alert_at, topology_snapshot, remediation_attempts, github_pr_url, rca_summary
`

type UpdateIncidentStateParams struct {
	ID    string `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateIncidentState(ctx context.Context, arg UpdateIncidentStateParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentState, arg.ID, arg.State)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Cluster,
		&i.Environment,
		&i.Severity,
		&i.CorrelationKey,
		&i.CorrelationVersion,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.TopologySnapshot,
		&i.RemediationAttempts,
		&i.GithubPrUrl,
		&i.RcaSummary,
	)
	return i, err
}
