// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          int32              `json:"id"`
	IncidentID  string             `json:"incident_id"`
	Fingerprint string             `json:"fingerprint"`
	Labels      json.RawMessage    `json:"labels"`
	Annotations json.RawMessage    `json:"annotations"`
	StartsAt    time.Time          `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Incident struct {
	ID                  string    `json:"id"`
	Service             string    `json:"service"`
	Cluster             string    `json:"cluster"`
	Environment         string    `json:"environment"`
	Severity            string    `json:"severity"`
	CorrelationKey      string    `json:"correlation_key"`
	CorrelationVersion  int32     `json:"correlation_version"`
	State               string    `json:"state"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	FirstAlertAt        time.Time `json:"first_alert_at"`
	LastAlertAt         time.Time `json:"last_alert_at"`
	TopologySnapshot    []byte    `json:"topology_snapshot"`
	RemediationAttempts int32     `json:"remediation_attempts"`
	GithubPrUrl         *string   `json:"github_pr_url"`
	RcaSummary          *string   `json:"rca_summary"`
}
