// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"context"
	"time"
)

type Querier interface {
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	FindOpenByCorrelationKey(ctx context.Context, arg FindOpenByCorrelationKeyParams) (Incident, error)
	GetAlertByFingerprint(ctx context.Context, fingerprint string) (Alert, error)
	GetAlertsByIncidentID(ctx context.Context, incidentID string) ([]Alert, error)
	GetIncidentByID(ctx context.Context, id string) (Incident, error)
	IncrementRemediationAttempts(ctx context.Context, id string) (Incident, error)
	ListIncidents(ctx context.Context) ([]Incident, error)
	ListIncidentsByState(ctx context.Context, state string) ([]Incident, error)
	ListRecentAlerts(ctx context.Context, startsAt time.Time) ([]Alert, error)
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error)
	UpdateIncidentPR(ctx context.Context, arg UpdateIncidentPRParams) (Incident, error)
	UpdateIncidentRCA(ctx context.Context, arg UpdateIncidentRCAParams) (Incident, error)
	UpdateIncidentState(ctx context.Context, arg UpdateIncidentStateParams) (Incident, error)
}

var _ Querier = (*Queries)(nil)
