apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentientd
  namespace: sentientd
  labels:
    app.kubernetes.io/name: sentientd
    app.kubernetes.io/component: incident-management
automountServiceAccountToken: true
